### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by ghost** [HiddenMotives/ProxyChecker#13]
How to i specify the Proxy list in the docker version?

**Comment by faiqsohail** [comment]
You would mount a volume to `/app`, for example if your proxy list is located in the directory `/User/Downloads/proxylist/` you would use the following flag in the docker run command `-v "/User/Downloads/proxylist:/app"`. 

When the application starts you would navigate to File -> Open, you would see the contents of the `proxylist` directory which you mounted.
