### ISSUE TITLE
Service Down

### ISSUE THREAD

**Issue by navik44** [HiddenMotives/ProxyChecker#18]
My internet is connected and working, but every time I run Proxy Checker, I get this error:

![1](https://user-images.githubusercontent.com/22314495/193541531-82e8b02d-36b8-4e14-9a18-d903d1d503d2.jpg)

I have to open Proxy Checker every time with VPN, but VPN is no longer needed to scan proxies and Proxy Checker works fine without VPN.

Can you please solve this problem?

**Comment by faiqsohail** [comment]
Why do you have to open the app with a VPN?

**Comment by navik44** [comment]
> Why do you have to open the app with a VPN?

Because I got Service Down error

In the past few days, the problem has been solved and the app opens without VPN.
